name: smtpdane tool release
on:
  push:
    tags:
      - 'v*'

permissions:
  # Control the GITHUB_TOKEN permissions; GitHub's docs on which permission scopes control what are a little lacking.
  # By having this block, all permissions not listed here are set to none.
  #
  # <https://goreleaser.com/ci/actions/> documents which scopes are needed for it.
  # Uploading archives as release artifacts is bundled into the contents: permission key!  (goreleaser documents as content: but it's contents:).
  # packages: is for pushing docker images to github (ghcr.io)
  # actions: is for uploading artifacts
  contents: write
  packages: write
  actions: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # NB: the `fetch-depth: 0` setting is documented by goreleaser
          # as a requirement, for the changelog feature to work correctly.
          fetch-depth: 0

      # If we had something suitable for a Docker image, here we would setup QEMU and BuildX

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          check-latest: true

      - name: Basic Go integrity checks
        run: |
          go vet ./...
          t="$(go list -m -retracted -f '{{if .Retracted}}::error file=go.mod::{{.Path}} is retracted{{end}}' all)"
          if [ ".$t" != "." ]; then printf '%s\n' "$t"; exit 1; fi

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


