name: smtpdane tool release
on:
  push:
    tags:
      - 'v*'

permissions:
  # Control the GITHUB_TOKEN permissions; GitHub's docs on which permission scopes control what are a little lacking.
  # By having this block, all permissions not listed here are set to none.
  #
  # <https://goreleaser.com/ci/actions/> documents which scopes are needed for it.
  # Uploading archives as release artifacts is bundled into the contents: permission key!  (goreleaser documents as content: but it's contents:).
  # packages: is for pushing docker images to github (ghcr.io)
  # actions: is for uploading artifacts
  contents: write
  packages: write
  actions: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # NB: the `fetch-depth: 0` setting is documented by goreleaser
          # as a requirement, for the changelog feature to work correctly.
          fetch-depth: 0
          # We don't need to work with the git remote after this, so:
          persist-credentials: false

      # If we had something suitable for a Docker image, here we would setup QEMU and BuildX

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 'stable'
          check-latest: true
          # We are producing a release artifact, so should accept the penalty
          # cost of uncached builds and avoid the risk of cache poisoning via
          # PRs.
          cache: false

      - name: Basic Go integrity checks
        run: |
          go vet ./...
          t="$(go list -m -retracted -f '{{if .Retracted}}::error file=go.mod::{{.Path}} is retracted{{end}}' all)"
          if [ ".$t" != "." ]; then printf '%s\n' "$t"; exit 1; fi

      - name: Version / Environment Reporting
        run: |
          ./build/show.versions

      - name: Run GoReleaser
        id: goreleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


